# Generated by Django 3.2.16 on 2023-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=150)),
                ('source', models.URLField()),
                ('submitted_by', models.EmailField(max_length=254)),
            ],
        ),
    ]
