# Generated by Django 4.1.5 on 2023-01-04 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_artist_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 1, 4, 3, 40, 31, 673693, tzinfo=datetime.timezone.utc), verbose_name='djangodbmodelsfieldscharfield'),
            preserve_default=False,
        ),
    ]
