# Generated by Django 4.1.5 on 2023-01-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
