# Generated by Django 4.1.5 on 2023-01-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_artist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='artist',
            name='user_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
