# Generated by Django 4.1.5 on 2023-01-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_remove_artist_submitted_by_artist_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
