# Generated by Django 4.1.5 on 2023-01-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_alter_artist_slug_alter_artist_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(),
        ),
    ]
