# Generated by Django 4.1.5 on 2023-01-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_alter_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='user_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
