# Generated by Django 4.1.5 on 2023-01-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_alter_artist_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
