# Generated by Django 4.1.5 on 2023-01-04 05:59

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('listing', '0011_artist_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Genres'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='link',
            field=models.URLField(verbose_name='URL To Artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Artist Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='notes',
            field=models.CharField(blank=True, max_length=150, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='source',
            field=models.URLField(blank=True, verbose_name='Source That The Artist Is Canadian'),
        ),
    ]
