# Generated by Django 4.1.5 on 2023-01-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_alter_artist_genres_alter_artist_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='source',
            field=models.URLField(blank=True, default='Warning: This artist has no source and may not actually be canadian! Proceed at your own risk.', verbose_name='Source That The Artist Is Canadian'),
        ),
    ]
