# Generated by Django 4.1.5 on 2023-01-04 18:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('listing', '0015_alter_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=taggit.managers.TaggableManager(help_text='A comma separated list of genres', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Genres'),
        ),
    ]
