# Generated by Django 4.1.5 on 2023-01-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_alter_artist_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='source',
            field=models.URLField(blank=True, verbose_name='Source That The Artist Is Canadian'),
        ),
    ]
